### PR TITLE
Update index.jade

### PR DESCRIPTION
**Pull request by fridays**
fixes user profile on mobiles

### CODE REVIEW

**Comment by rickhanlonii** [comment]
@fridays looks like linting failed. Care to take a look? 

I also noticed you're not in `userlist.js`, want to add yourself there as well?

**Comment by fridays** [comment]
@rickhanlonii Checks failed because of the userlist bug which is now fixed. I tried to merge the master branch, not sure if I am doing this right.

**Comment by rickhanlonii** [comment]
@fridays that fixed it, thanks!

I took a look at this and it seems that mobile was improved but desktop is kinda broken. 

A couple thoughts (see screens):

- Mobile could be a bit tighter
- Inline may have worked better on both
- Desktop and mobile should have the name next to the picture
- Desktop should have the info right-aligned, not center aligned

## Screens 

#### Mobile Before / After


Here's the difference on desktop:

#### Desktop Before


#### Desktop After



Mind making some updates?

**Comment by rickhanlonii** [comment]
@fridays I think I took care of this in https://github.com/larvalabs/pullup/pull/386. Let me know if this can be closed.

**Comment by rickhanlonii** [comment]
Hey @fridays, this is quite out of date with master now so I'm going to close.

**Pull request closed without merging**
