### PR TITLE
Update userlist.js

### PR DESCRIPTION
**Pull request by fridays**
sign up

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Broken due to bug fixed on https://github.com/larvalabs/pullup/pull/380.

**Comment by rickhanlonii** [comment]
@megamattron this should pass linting after merging master.

**Comment by megamattron** [comment]
@rickhanlonii Does this mean that @fridays needs to merge master, or I should do it?

**Comment by rickhanlonii** [comment]
@megamattron sorry for the confusion, @fridays could merge master into this branch to verify tests pass but it's so basic that I think it's safe for you to merge as-is.

**Comment by rickhanlonii** [comment]
Welcome @fridays, please take a look at https://github.com/larvalabs/pullup/pull/378 when you get a chance.

**Pull request merged**
